apiVersion: v2
name: wallet-service
description: Production-grade Helm Chart for A Bank Mobile Wallet Service
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Thaw Zin @ Chris (SRE Team)
    email: pretamane@users.noreply.github.com
