# ==============================================================================
# A Bank Hybrid Infrastructure - Ansible Inventory
# Architecture: On-Prem Bare-Metal / Edge K3s Clusters & Cloud Gateway
# ==============================================================================

[onprem_baremetal_nodes]
# Primary On-Prem Bare-Metal Nodes for Core Financial Ledger & Branch Gateways
ledger-node-01.abank.local ansible_host=10.200.10.11 ansible_user=sreadmin
ledger-node-02.abank.local ansible_host=10.200.10.12 ansible_user=sreadmin

[k3s_control_plane]
k3s-master-01.abank.local  ansible_host=10.200.20.10 ansible_user=sreadmin

[k3s_workers]
k3s-worker-01.abank.local  ansible_host=10.200.20.21 ansible_user=sreadmin
k3s-worker-02.abank.local  ansible_host=10.200.20.22 ansible_user=sreadmin

[k3s_cluster:children]
k3s_control_plane
k3s_workers

[hybrid_fintech_fleet:children]
onprem_baremetal_nodes
k3s_cluster
